Kczernik/papp 35149
splunk-soar-connectors/confluence pull request #7
Opened 2024-11-27 21:04 UTC by mctonderski-splunk

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2024-12-02 09:02 UTC, kczernik-splunk commented on confluence_connector.py
> +        self.save_progress(f"username: {self._username} api: {self._apiToken}")
I'm not sure but saving_progress with a token doesn't seem to be the best idea.

2024-12-02 14:38 UTC, bb-splunk requested changes

2024-12-02 14:38 UTC, bb-splunk commented on confluence.json
>      "pip39_dependencies": {
Removing this whole key should work

2024-12-02 14:38 UTC, bb-splunk commented on confluence_connector.py
> +DEFAULT_REQUEST_TIMEOUT = 30  # Timeout for requests
The previous comment added some information, the new one is 100% redundant given the variable name

2024-12-02 14:38 UTC, bb-splunk commented on confluence_connector.py
> +        if hasattr(action_result, "add_debug_data"):
I assume this `if` is for compatibility with some ancient SOAR version and can be removed.

2024-12-02 14:38 UTC, bb-splunk commented on confluence_connector.py
> +        self._base_path = config.get("base_path", "")
No `get`s necessary if those are required

2024-12-02 14:38 UTC, bb-splunk commented on confluence_connector.py
> +        url = f"{self._base_url}{self._base_path}{endpoint}"
How do we not end up with something like `xyz.comsomepathendpoint` instead of `xyz.com/somepath/endpoint`?

2024-12-02 14:38 UTC, bb-splunk commented on confluence_connector.py
> +        self._base_url = config["base_url"].rstrip("/")
Why split URL from path? They're ever only used together.

2024-12-04 09:35 UTC, mctonderski-splunk commented on confluence_connector.py
> +        url = f"{self._base_url}{self._base_path}{endpoint}"
Okay fair point I modified path making to make sure it's properly formatted.

2024-12-04 12:00 UTC, mposluszny-splunk requested changes
* Please fill up the MR description and change it title so it give more information about changes
* Fill up unreleased.md file

2024-12-04 13:34 UTC, bb-splunk approved these changes

2024-12-04 13:34 UTC, bb-splunk commented on confluence_connector.py
> +        self._apiToken = None
Why not `_api_token`?

2024-12-04 14:06 UTC, mposluszny-splunk commented
@mctonderski-splunk what about failing:
- sanity-tests
- integration-tests
- prodsec-scans?

2024-12-04 14:49 UTC, mctonderski-splunk commented
So currently we don't have any asset that supports API v2, it's an ongoing process to get that set up. It was tested on the newest dummy confluence instance.

2024-12-04 14:52 UTC, mposluszny-splunk approved these changes

2024-12-04 14:53 UTC, merged